### ISSUE TITLE
Out of curiosity, is this equivalent? 

### ISSUE THREAD

**Issue by nilslice** [tidwall/limiter#1]
```go
package limiter

// Limiter is for limiting the number of concurrent operations. This
type Limiter struct {
	limit int
	sem   chan struct{}
}

// New returns a new Limiter. The limit param is the maximum number of
// concurrent operations.
func New(limit int) *Limiter {
	return &Limiter{
		limit: limit,
		sem:   make(chan struct{}, limit),
	}
}

// Begin an operation.
func (l *Limiter) Begin() {
	l.sem <- struct{}{}
}

// End the operation.
func (l *Limiter) End() {
	<-l.sem
}
```

**Comment by tidwall** [comment]
yeah. pretty much. 
I'm not sure what the performance difference would be. 
I suspect buffered channels might be a little faster??? I dunno for sure. 
Another option is to use sync.WaitGroup which has some really efficient semaphore stuff under the hood which.

**Comment by nilslice** [comment]
Good to know!

I was excited to see the use of sync.Cond, which admittedly I have never reached for myself, and don't fully grasp. This helped me get a better idea though 👍

**Comment by tidwall** [comment]
FYI, I just did a benchmark and the buffered channel is faster!

**Comment by nilslice** [comment]
The channel is a pretty awesome tool! Quite interesting to see how many less operations  in comparison.
